### ISSUE TITLE
Make the I/O functions separately installable?

### ISSUE THREAD

**Issue by slwatkins** [berkeleytes/pytesdaq#10]
Would it be possible to make the I/O functions separately installable? I'm thinking along the lines of making them a separate package, like CDMS did with `pyrawio`. Or, maybe we could add an option to the installation that only installs the I/O functions and not the rest?

My reason for asking this is that, when trying to install on Galba, I was unable to install PyQt5. But, I think this is only used for the scope parts of the package, whereas I only needed to use I/O functions.

It's not urgent (I used the SLAC Jupyter Hub instead, which didn't have the same problem). But, we might in the future want to do this so that when we write code that needs the I/O functions, it doesn't require the entire DAQ package to be installed.

**Comment by cwfink** [comment]
I agree that it would be nice to have the I/O functionality be in its own package. I was able to install the full package just fine, but from a package management point of view, moving forward it would make sense to separate this into two distinct packages.

**Comment by serfass** [comment]
Sounds like a good idea. Let's talk about it in January.

**Comment by slwatkins** [comment]
Closing this, since I no longer have this problem and I don't think it's worth our time to do this.
